ansible_python_interpreter: /usr/bin/python3
ansible_connection: ssh
ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
ansible_user: vagrant
ansible_port: 2222