services:
  ic-webapp:
    container_name: ic-webapp
    image: stephaneds/ic-webapp:${VERSION:-1.0}
    ports:
      - "${IC_WEBAPP_PORT:-8080}:8080"
    environment:
      - ODOO_URL=${ODOO_URL:-https://odoo.com/}
      - PGADMIN_URL=${PGADMIN_URL:-https://pgadmin.org/}
    networks:
      - ${DOCKER_NETWORK:-ic-network}

networks:
  ic-network:
    driver: bridge
    name: ic-network
