services:
    pgadmin4:
        ports:
            - 5050:80
        volumes:
            - /tmp/servers.json:/pgadmin4/servers.json
            - pgadmin-data:/var/lib/pgadmin
            
        environment:
            - PGADMIN_DEFAULT_EMAIL=user@domain.com
            - PGADMIN_DEFAULT_PASSWORD=SuperSecret
        image: dpage/pgadmin4
        container_name: pgadmin4
        networks:
            - ic-network

networks:
    ic-network:
        driver: bridge
        name: ic-network
        external: true

volumes:
    pgadmin-data:
        
