apiVersion: v1
data:
  POSTGRES_PASSWORD: bXlvZG9v
  POSTGRES_USER: b2Rvbw==
kind: Secret
metadata:
  creationTimestamp: null
  name: odoo-db-secret
  namespace: ic-group
  labels:
    app: odoo-db
    env: prod
